### ISSUE TITLE
Enable linting on Windows platform in GitHub Actions CI

### ISSUE THREAD

**Issue by austinvazquez** [aws/shim-loggers-for-containerd#50]
During https://github.com/aws/amazon-ecs-shim-loggers-for-containerd/pull/41, I found the Windows platform test and linting was not being ran. I was able to get test work, but linting was more effort and I did not want to block addressing other CI issues.

This task would be to enable linting on the Windows platform and address any issues found.

**Comment by ningziwen** [comment]
Based on this converation https://github.com/aws/shim-loggers-for-containerd/pull/57#discussion_r1269874333, Windows linter is not needed? Could we close the issue?
